### ISSUE TITLE
Don't set __package__

### ISSUE THREAD

**Issue by rchl** [HuygensING/LSP-tagml#3]
`__package__` is set automatically and reflects the directory of your package. No need to set it manually. It can even cause issues if your package is named differently on PackageControl.
https://github.com/HuygensING/LSP-tagml/blob/698e114e1893849d193b6c46b02b349f3f44d330/plugin.py#L13

**Comment by brambg** [comment]
OK, I misinterpreted your earlier issue.
Hope this change is what you had in mind.

**Comment by rchl** [comment]
Yes :)

**Comment by rchl** [comment]
Now you are setting `PACKAGE_NAME` to `__package__` but not using `PACKAGE_NAME` anywhere. Either use `PACKAGE_NAME` where you use `__package__` now or just use `__package__` everywhere and remove `PACKAGE_NAME`.

**Comment by brambg** [comment]
I see. Re-reading the code more thoroughly, I guess that line was a leftover from an earlier version, and can be removed.
