### ISSUE TITLE
Why disabled?

### ISSUE THREAD

**Issue by rchl** [HuygensING/LSP-tagml#4]
https://github.com/HuygensING/LSP-tagml/blob/0738ed744680751fd24fc6a157e460767bffc371/plugin.py#L156-L170

**Comment by brambg** [comment]
Assuming this comment was referring to the commented-out on_start, I've removed these lines of code

**Comment by rchl** [comment]
Yes, sorry, I updated my comment.

I haven't checked if it's all correct but I think it would make sense to enable this code rather than removing. If the session is started before the server was installed then things will fail and in more noisy way than if you handle it here.

**Comment by brambg** [comment]
OK, I see. In testing I didn't think this method was called, I'll try it again.

**Comment by rchl** [comment]
It gets called when opening supported file, before session is started. If the server is not installed yet then `on_start` should return false.
